In [ ]:
import pandas as pd
import numpy as np
import nltk

file_path = 'CS173-publishedsheet.xlsx'  # Replace with your Excel file path
df = pd.read_excel(file_path)
# Remove newline characters from all cells
df = df.replace({r'\n': ' '}, regex=True)
print(df)
# Save the modified data back to a new Excel file
#output_file_path = 'modified_file.xlsx'
# Replace with the desired output file path
#output_file = df.to_excel(output_file_path, index=False, engine='openpyxl')
#file = pd.read_csv("CS173-published-sheet.csv")
#file = file.replace({r'\n':''}, regex=True)
#output_file = file.to_excel()

                                     Sadness Lexicons  \
0                                abduction, devastate   
1                                   wretched, wrongly   
2                                   Stifle, Mausoleum   
3   abandon,abandoned,abandonment,abduction,aborti...   
4                                              lonely   
5                                 wrongful, abandoned   
6                                               agony   
7                          Blunder, crushed, tragedy    
8                                     Lonely, longing   
9         Robbery, Dying, Hospital, Crippled, Horror    
10  Sufferer, homesick, remorse, lowest, devastati...   
11                 Agony, savage, betrayed, stripped    
12                                               ache   
13                                            abysmal   
14  desert, undesirable, deceased, desolation, wee...   
15                 Disconnect, Damages, Unsuccessful,   
16                             

# Section 2 - Preprocessing the Data

In [ ]:
drop_columns = ['Sadness Lexicons', 'Joy Lexicons', 'Fear Lexicons', 'Anger Lexicons', 'Surprise Lexicons', 'Disgust Lexicons', 'Sadness + Joy Lexicons', 'Fear + Anger Lexicons', 'Surprise + Disgust Lexicons', 'Sadness + Joy + Fear Lexicons']
df = df.drop(drop_columns, axis=1).dropna()


In [ ]:
training_set = df.iloc[:30]
#training_set
validation_set = df.iloc[31:41]
#validation_set
testing_set = df.iloc[42:]
#testing_set
print(len(training_set))
print(len(validation_set))
print(len(testing_set))

# getting rid of ' ' (empty cells)
training_set = training_set.apply(lambda x: pd.Series(x.dropna().values)).fillna(' ')
#print(len(training_set))


#IGNORE THIS (was trying something, did not work. )
sadnessSet = df[['Sadness Sentences']]
joySet = df[['Joy Sentences']]
fearSet = df[['Fear Sentences']]
angerSet = df[['Anger Sentences']]
surpriseSet = df[['Surprise Sentence']]
disgustSet = df[['Disgust Sentences']]
sadJoySet = df[['Sadness + Joy Sentences']]
fearAngerSet = df[['Fear + Anger Sentences']]
surpriseDisgustSet = df[['Surprise + Disgust Sentences']]
sadJoyFearSet = df[['Sadness + Joy + Fear Sentences']]

training_sadSet = sadnessSet[:30]

30
10
3


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.corpus import inaugural

#training_set = training_set.replace()

#words = 0
nltk.download('punkt')
# tokenizes first row for 6 emotion sentences
sadness_sent = training_set.iloc[0]['Sadness Sentences']
joy_sent = training_set.iloc[0]['Joy Sentences']
fear_sent = training_set.iloc[0]['Fear Sentences']
anger_sent = training_set.iloc[0]['Anger Sentences']
surprise_sent = training_set.iloc[0]['Surprise Sentence']
disgust_sent = training_set.iloc[0]['Disgust Sentences']

sadness_joy_sent = training_set.iloc[0]['Sadness + Joy Sentences']
fear_anger_sent = training_set.iloc[0]['Fear + Anger Sentences']
surprise_disgust_sent = training_set.iloc[0]['Surprise + Disgust Sentences']
sad_joy_fear_sent = training_set.iloc[0]['Sadness + Joy + Fear Sentences']
corpus = [sadness_sent, joy_sent, fear_sent, anger_sent, surprise_sent, disgust_sent, sadness_joy_sent, fear_anger_sent, surprise_disgust_sent, sad_joy_fear_sent]
training_set.head(1)

tokenized_text = []
for sentence in corpus:
  textTokenize = []
  stemp = sent_tokenize(sentence)
  #print(stemp)
  tokens = word_tokenize(sentence)
  #print(tokens)
  textTokenize.append(tokens)
  #textTokenize.append('\n')
  tokenized_text.append(textTokenize)

for t in tokenized_text:
  print(t)
  print("\n")


[['The', 'devastating', 'news', 'of', 'the', 'child', "'s", 'abduction', 'left', 'a', 'solemn', 'shadow', 'over', 'the', 'family', 'for', 'the', 'next', 'month', '.']]


[['It', 'was', 'a', 'sunny', 'summer', 'morning', 'and', 'the', 'laughter', 'of', 'children', 'could', 'be', 'heard', 'from', 'the', 'pool', 'as', 'they', 'splashed', 'water', 'onto', 'each', 'other', '.']]


[['As', 'he', 'walked', 'in', 'the', 'dead', 'of', 'night', 'he', 'could', 'hear', 'sudden', 'footsteps', 'echoing', 'from', 'the', 'alleyway', ',', 'a', 'shiver', 'went', 'down', 'his', 'spine', '.']]


[['While', 'driving', 'his', 'family', 'to', 'a', 'restaurant', 'a', 'car', 'recklessly', 'changed', 'lanes', 'barely', 'missing', 'him', ',', 'his', 'face', 'flushed', 'red', 'with', 'fury', 'knowing', 'how', 'close', 'his', 'family', 'was', 'to', 'being', 'seriously', 'harmed', '.']]


[['She', 'was', 'startled', 'unexpectedly', 'as', 'everyone', 'sprang', 'from', 'their', 'hiding', 'spot', 'to', 'celebrate', 'h

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


### Stopwords

In [ ]:
from nltk.corpus import stopwords
nltk.download('stopwords')
stops = set(stopwords.words('english'))
print(stops)

{'she', 'own', 'the', 'him', 'yours', 'up', 'its', 'that', 'because', 'hadn', 'hers', 'whom', 't', 'again', 'to', 'our', 'those', 'why', "wasn't", 'ours', "needn't", 'needn', "weren't", "you'll", 'under', 'can', 'after', 'should', "aren't", 'mustn', "shouldn't", 'weren', 'were', 'you', 'further', 'until', 'what', "shan't", 'who', 'for', 'at', 'so', 'my', 'below', 'be', 'it', "it's", 'before', 'each', 'ain', 'aren', "doesn't", 're', 'shouldn', 'more', 'having', 'where', 'yourself', 'will', 'didn', 'very', 'myself', 'does', 'll', 'doing', 'during', 'don', 'shan', 'won', 'am', 'above', 'is', 'a', 'they', 'other', 'i', 'mightn', "mightn't", 'over', 'there', 'some', 'if', 'off', 'now', 'did', 'was', "won't", "you've", 'doesn', 'too', 'than', 'this', 'an', 'himself', 'down', 'itself', 'not', 'same', "wouldn't", "that'll", 'd', "should've", 'do', 'hasn', 'as', 'm', "you'd", 'couldn', "couldn't", "hasn't", "you're", 'theirs', 'which', 'such', "haven't", 'me', "isn't", "mustn't", 'herself', 'of

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


### lower function (From Disucssion 1)

In [ ]:
def lower(lists):
  return [x.lower() for x in lists]


# Section 3 - Naive Bayes Classifier

In [ ]:
# full_corpus
sadness = []
joy = []
fear = []
anger = []
surprise = []
disgust = []
sad_joy = []
fear_anger = []
surprise_disgust = []
sad_joy_fear = []

unique_words = list()

for i in range(len(training_set)):
  sadness_sent = training_set.iloc[i]['Sadness Sentences']
  joy_sent = training_set.iloc[i]['Joy Sentences']
  fear_sent = training_set.iloc[i]['Fear Sentences']
  anger_sent = training_set.iloc[i]['Anger Sentences']
  surprise_sent = training_set.iloc[i]['Surprise Sentence']
  disgust_sent = training_set.iloc[i]['Disgust Sentences']

  sadness_joy_sent = training_set.iloc[i]['Sadness + Joy Sentences']
  fear_anger_sent = training_set.iloc[i]['Fear + Anger Sentences']
  surprise_disgust_sent = training_set.iloc[i]['Surprise + Disgust Sentences']
  sad_joy_fear_sent = training_set.iloc[i]['Sadness + Joy + Fear Sentences']

  corpus = [sadness_sent, joy_sent, fear_sent, anger_sent, surprise_sent, disgust_sent, sadness_joy_sent, fear_anger_sent, surprise_disgust_sent, sad_joy_fear_sent]
  for sent in corpus:
    words = sent.split(' ')
    words = lower(words)
    for word in words:
      if word not in unique_words:
        unique_words.append(word)

  sadness.append(sadness_sent)
  joy.append(joy_sent)
  fear.append(fear_sent)
  anger.append(anger_sent)
  surprise.append(surprise_sent)
  disgust.append(disgust_sent)

  sadness.append(sadness_joy_sent)
  joy.append(sadness_joy_sent)

  fear.append(fear_anger_sent)
  anger.append(fear_anger_sent)

  surprise.append(surprise_disgust_sent)
  disgust.append(surprise_disgust_sent)

  sadness.append(sad_joy_fear_sent)
  joy.append(sad_joy_fear_sent)
  fear.append(sad_joy_fear_sent)

print(len(unique_words))
N = len(unique_words) # Grab unique words


2540


## Section 3.1

In [ ]:
# Section 3.1
n_sad = len(sadness)
n_joy = len(joy)
n_fear = len(fear)
n_anger = len(anger)
n_surprise = len(surprise)
n_disgust = len(disgust)
print(n_sad)
print(n_joy)
print(n_fear)
print(n_anger)
print(n_surprise)
print(n_disgust)
total = n_sad + n_joy + n_fear + n_anger + n_surprise + n_disgust
print(total)
print("P(Fear) = ", n_fear / total)
p_fear = n_fear / total
print("P(Anger) = ", n_anger / total)
p_anger = n_anger / total
print("P(Surprise) = ", n_surprise / total)
p_surprise = n_surprise / total
print("P(Disgust) = ", n_disgust / total)
p_disgust = n_disgust / total
print("P(Joy) = ", n_joy / total)
p_joy = n_joy / total
print("P(Sadness) = ", n_sad / total)
p_sad = n_sad / total

90
90
90
60
60
60
450
P(Fear) =  0.2
P(Anger) =  0.13333333333333333
P(Surprise) =  0.13333333333333333
P(Disgust) =  0.13333333333333333
P(Joy) =  0.2
P(Sadness) =  0.2


In [ ]:
sadset = []
joyset = []
fearset = []
angerset = []
surpriseset = []
disgustset = []

unique = []


for i in range(len(validation_set)):
  sadness_sent = training_set.iloc[i]['Sadness Sentences']
  joy_sent = training_set.iloc[i]['Joy Sentences']
  fear_sent = training_set.iloc[i]['Fear Sentences']
  anger_sent = training_set.iloc[i]['Anger Sentences']
  surprise_sent = training_set.iloc[i]['Surprise Sentence']
  disgust_sent = training_set.iloc[i]['Disgust Sentences']

  sadness_joy_sent = training_set.iloc[i]['Sadness + Joy Sentences']
  fear_anger_sent = training_set.iloc[i]['Fear + Anger Sentences']
  surprise_disgust_sent = training_set.iloc[i]['Surprise + Disgust Sentences']
  sad_joy_fear_sent = training_set.iloc[i]['Sadness + Joy + Fear Sentences']

  corpus = [sadness_sent, joy_sent, fear_sent, anger_sent, surprise_sent, disgust_sent, sadness_joy_sent, fear_anger_sent, surprise_disgust_sent, sad_joy_fear_sent]
  for sent in corpus:
    words = sent.split(' ')
    words = lower(words)
    for word in words:
      if word not in unique:
        unique.append(word)

  sadset.append(sadness_sent)
  joyset.append(joy_sent)
  fearset.append(fear_sent)
  angerset.append(anger_sent)
  surpriseset.append(surprise_sent)
  disgustset.append(disgust_sent)

  sadset.append(sadness_joy_sent)
  joyset.append(sadness_joy_sent)
  sadset.append(sad_joy_fear_sent)
  joyset.append(sad_joy_fear_sent)
  fearset.append(fear_anger_sent)
  fearset.append(sad_joy_fear_sent)
  surpriseset.append(surprise_disgust_sent)
  disgustset.append(surprise_disgust_sent)




## Section 3.2

In [ ]:
#p(w_i | c) = p(word | emotion) = p('sudden' | fear )

fear_freq = dict()
for sentence in fear:
  #print(sentence)
  words = sentence.split(' ')
  words = lower(words)

  #print(words)
  for word in words:
    if word in stops:
      words.remove(word)

    if word not in fear_freq:
      fear_freq[word] = 1
    else:
      fear_freq[word] += 1

#print(len(fear_freq))
for k, v in fear_freq.items():
  #print(k, v)
  num = v + 1
  denom = v + N
  #print(num, denom)
  print(k, num / denom)
  #print(k, (v+1) / v+N)


as 0.014745828482731859
walked 0.0007870916961826052
in 0.013980582524271845
dead 0.0007870916961826052
of 0.030175706646294882
he 0.008590394377196407
hear 0.0007870916961826052
sudden 0.0007870916961826052
 0.005094043887147335
footsteps 0.0007870916961826052
echoing 0.0007870916961826052
from 0.003532182103610675
alleyway, 0.0007870916961826052
a 0.011677695601401323
went 0.0007870916961826052
down 0.0015729453401494297
spine. 0.0007870916961826052
tom 0.0011801730920535012
was 0.0101364522417154
bully 0.0007870916961826052
and 0.02044753086419753
docile 0.0007870916961826052
while 0.0015729453401494297
being 0.0007870916961826052
on 0.005873140172278779
avoid 0.0007870916961826052
provoking 0.0007870916961826052
the 0.0360668185269552
into 0.0027494108405341712
fit 0.0007870916961826052
where 0.0011801730920535012
may 0.0011801730920535012
be 0.002357563850687623
harmed. 0.0007870916961826052
watched 0.0007870916961826052
their 0.0019654088050314465
leave 0.0011801730920535012
for 

In [ ]:
anger_freq = dict()
for sentence in anger:
  #print(sentence)
  words = sentence.split(' ')
  words = lower(words)

  #print(words)
  for word in words:
    if word in stops:
      words.remove(word)

    if word not in anger_freq:
      anger_freq[word] = 1
    else:
      anger_freq[word] += 1

#print(len(fear_freq))
for k, v in anger_freq.items():
  #print(k, v)
  num = v + 1
  denom = v + N
  #print(num, denom)
  print(k, num / denom)
  #print(k, (v+1) / v+N)

while 0.0019654088050314465
his 0.005483744614179397
to 0.010522213561964146
restaurant 0.0007870916961826052
a 0.007815552950371238
recklessly 0.0007870916961826052
 0.004313725490196078
changed 0.0007870916961826052
lanes 0.0007870916961826052
barely 0.0007870916961826052
missing 0.0007870916961826052
him, 0.0007870916961826052
flushed 0.0007870916961826052
red 0.0007870916961826052
with 0.004313725490196078
knowing 0.0011801730920535012
how 0.0019654088050314465
close 0.0007870916961826052
was 0.005873140172278779
being 0.0015729453401494297
harmed. 0.0011801730920535012
tom 0.0007870916961826052
of 0.016272762495156915
bully 0.0007870916961826052
and 0.013597513597513598
docile 0.0007870916961826052
on 0.0027494108405341712
avoid 0.0007870916961826052
provoking 0.0007870916961826052
the 0.02120277563608327
into 0.0015729453401494297
fit 0.0011801730920535012
where 0.0011801730920535012
may 0.0007870916961826052
be 0.0011801730920535012
we 0.0011801730920535012
abolish 0.00078709169

In [ ]:
surprise_freq = dict()
for sentence in surprise:
  #print(sentence)
  words = sentence.split(' ')
  words = lower(words)

  #print(words)
  for word in words:
    if word in stops:
      words.remove(word)

    if word not in surprise_freq:
      surprise_freq[word] = 1
    else:
      surprise_freq[word] += 1

#print(len(fear_freq))
for k, v in surprise_freq.items():
  #print(k, v)
  num = v + 1
  denom = v + N
  #print(num, denom)
  print(k, num / denom)
  #print(k, (v+1) / v+N)

she 0.004704037632301058
startled 0.0011801730920535012
unexpectedly 0.002357563850687623
as 0.007815552950371238
sprang 0.0007870916961826052
from 0.003923107100823852
their 0.0007870916961826052
spot 0.0007870916961826052
to 0.011292834890965732
her 0.004313725490196078
he 0.004313725490196078
the 0.02082529888160432
of 0.01436335403726708
food 0.0007870916961826052
delivery 0.0007870916961826052
and 0.0062622309197651665
shocked 0.0019654088050314465
a 0.008203125
insect 0.0007870916961826052
laying 0.0007870916961826052
on 0.003532182103610675
his 0.0031409501374165686
eating 0.0007870916961826052
it 0.002357563850687623
him. 0.0007870916961826052
out 0.003532182103610675
yelp 0.0015729453401494297
when 0.007039499413375049
friend 0.0011801730920535012
jumped 0.0007870916961826052
bewildered 0.0011801730920535012
by 0.002357563850687623
appalling 0.0007870916961826052
behavior. 0.0007870916961826052
alarms 0.0007870916961826052
jolts 0.0007870916961826052
me 0.005483744614179397
em

In [ ]:
disgust_freq = dict()

for sentence in disgust:
  #print(sentence)
  words = sentence.split(' ')
  words = lower(words)

  #print(words)
  for word in words:
    if word in stops:
      words.remove(word)

    if word not in disgust_freq:
      disgust_freq[word] = 1
    else:
      disgust_freq[word] += 1

#print(len(fear_freq))
for k, v in disgust_freq.items():
  #print(k, v)
  num = v + 1
  denom = v + N
  #print(num, denom)
  print(k, num / denom)
  #print(k, (v+1) / v+N)

she 0.003923107100823852
forgotten 0.0007870916961826052
to 0.011292834890965732
out 0.0015729453401494297
trash 0.0011801730920535012
before 0.0011801730920535012
for 0.0031409501374165686
holiday, 0.0007870916961826052
when 0.0062622309197651665
returned 0.0007870916961826052
repulsed 0.0007870916961826052
by 0.004313725490196078
stench 0.0015729453401494297
of 0.013597513597513598
food. 0.0007870916961826052
he 0.003532182103610675
the 0.02270977675134719
food 0.0011801730920535012
delivery 0.0007870916961826052
and 0.008203125
shocked 0.0007870916961826052
a 0.009750390015600624
insect 0.0007870916961826052
laying 0.0007870916961826052
on 0.0031409501374165686
his 0.004313725490196078
eating 0.0007870916961826052
it 0.0027494108405341712
him. 0.0011801730920535012
slime 0.0007870916961826052
emitted 0.0007870916961826052
an 0.0015729453401494297
smell. 0.0007870916961826052
bewildered 0.0011801730920535012
appalling 0.0007870916961826052
behavior. 0.0011801730920535012
left 0.00157

In [ ]:
joy_freq = dict()

for sentence in joy:
  #print(sentence)
  words = sentence.split(' ')
  words = lower(words)

  #print(words)
  for word in words:
    if word in stops:
      words.remove(word)

    if word not in joy_freq:
      joy_freq[word] = 1
    else:
      joy_freq[word] += 1

#print(len(fear_freq))
for k, v in joy_freq.items():
  #print(k, v)
  num = v + 1
  denom = v + N
  #print(num, denom)
  print(k, num / denom)
  #print(k, (v+1) / v+N)

it 0.005094043887147335
a 0.011677695601401323
summer 0.0007870916961826052
morning 0.0007870916961826052
and 0.016272762495156915
laughter 0.0007870916961826052
of 0.02980512036683225
children 0.0007870916961826052
could 0.0027494108405341712
be 0.003532182103610675
from 0.0031409501374165686
pool 0.0007870916961826052
as 0.015509887553315239
splashed 0.0007870916961826052
water 0.0007870916961826052
onto 0.0007870916961826052
each 0.0007870916961826052
when 0.003532182103610675
visited 0.0007870916961826052
my 0.005873140172278779
childhood 0.0007870916961826052
home, 0.0007870916961826052
i 0.015128006206361521
bittersweet 0.0007870916961826052
nostalgia 0.0007870916961826052
remembered 0.0007870916961826052
the 0.03349828701941378
memories 0.0015729453401494297
in 0.012830482115085537
house, 0.0011801730920535012
 0.005873140172278779
while 0.0019654088050314465
feeling 0.0019654088050314465
melancholy 0.0007870916961826052
never 0.0011801730920535012
get 0.0007870916961826052
to 0

In [ ]:
sad_freq = dict()

for sentence in sadness:
  #print(sentence)
  words = sentence.split(' ')
  words = lower(words)

  #print(words)
  for word in words:
    if word in stops:
      words.remove(word)

    if word not in sad_freq:
      sad_freq[word] = 1
    else:
      sad_freq[word] += 1

#print(len(fear_freq))
for k, v in sad_freq.items():
  #print(k, v)
  num = v + 1
  denom = v + N
  #print(num, denom)
  print(k, num / denom)
  #print(k, (v+1) / v+N)

the 0.030916030534351144
news 0.0007870916961826052
of 0.027575641516660282
child's 0.0007870916961826052
abduction 0.0007870916961826052
left 0.002357563850687623
a 0.01090767432800935
solemn 0.0007870916961826052
shadow 0.0007870916961826052
over 0.0015729453401494297
family 0.0007870916961826052
for 0.008590394377196407
next 0.0015729453401494297
month. 0.0007870916961826052
when 0.003532182103610675
visited 0.0007870916961826052
my 0.007815552950371238
childhood 0.0007870916961826052
home, 0.0007870916961826052
i 0.015509887553315239
bittersweet 0.0007870916961826052
nostalgia 0.0007870916961826052
as 0.012830482115085537
remembered 0.0011801730920535012
memories 0.0015729453401494297
in 0.011292834890965732
house, 0.0015729453401494297
 0.0062622309197651665
while 0.0015729453401494297
feeling 0.0027494108405341712
melancholy 0.0007870916961826052
never 0.0015729453401494297
get 0.0007870916961826052
to 0.02421214450422752
those 0.0019654088050314465
again. 0.0011801730920535012
w

In [ ]:
fear_prob = dict()
for k, v in fear_freq.items():
  num = v + 1
  denom = v + N
  fear_prob[k] = num / denom

anger_prob = dict()
for k, v in anger_freq.items():
  num = v + 1
  denom = v + N
  anger_prob[k] = num / denom

surprise_prob = dict()
for k, v in surprise_freq.items():
  num = v + 1
  denom = v + N
  surprise_prob[k] = num / denom

disgust_prob = dict()
for k, v in disgust_freq.items():
  num = v + 1
  denom = v + N
  disgust_prob[k] = num / denom

joy_prob = dict()
for k, v in joy_freq.items():
  num = v + 1
  denom = v + N
  joy_prob[k] = num / denom

sad_prob = dict()
for k, v in sad_freq.items():
  num = v + 1
  denom = v + N
  sad_prob[k] = num / denom

In [ ]:
train_sad_prob = []
train_joy_prob = []
train_fear_prob = []
train_anger_prob = []
train_surprise_prob = []
train_disgust_prob = []

for i in range(len(training_set)):
  sadness_sent = training_set.iloc[i]['Sadness Sentences']
  joy_sent = training_set.iloc[i]['Joy Sentences']
  fear_sent = training_set.iloc[i]['Fear Sentences']
  anger_sent = training_set.iloc[i]['Anger Sentences']
  surprise_sent = training_set.iloc[i]['Surprise Sentence']
  disgust_sent = training_set.iloc[i]['Disgust Sentences']

  sadness_joy_sent = training_set.iloc[i]['Sadness + Joy Sentences']
  fear_anger_sent = training_set.iloc[i]['Fear + Anger Sentences']
  surprise_disgust_sent = training_set.iloc[i]['Surprise + Disgust Sentences']
  sad_joy_fear_sent = training_set.iloc[i]['Sadness + Joy + Fear Sentences']

  corpus = [sadness_sent, joy_sent, fear_sent, anger_sent, surprise_sent, disgust_sent, sadness_joy_sent, fear_anger_sent, surprise_disgust_sent, sad_joy_fear_sent]
  for sent in corpus:
    words = sent.split(' ')
    words = lower(words)
    for word in words:
      if word in stops:
        words.remove(word)

    for word in words:
      if word not in unique_words:
        unique_words.append(word)

  train_given_sad = 1
  for w, val in sad_prob.items():
    if w in sadness_sent or w in sadness_joy_sent or w in sad_joy_fear_sent:
      train_given_sad *= val
  train_sad_prob.append(train_given_sad)

  train_given_joy = 1
  for w, val in joy_prob.items():
    if w in joy_sent or w in sadness_joy_sent or w in sad_joy_fear_sent:
      train_given_joy *= val
  train_joy_prob.append(train_given_joy)

  train_given_fear = 1
  for w, val in fear_prob.items():
    if w in fear_sent or w in fear_anger_sent or w in sad_joy_fear_sent:
      train_given_fear *= val
  train_fear_prob.append(train_given_fear)

  train_given_anger = 1
  for w, val in anger_prob.items():
    if w in anger_sent or w in fear_anger_sent:
      train_given_anger *= val
  train_anger_prob.append(train_given_anger)

  train_given_surprise = 1
  for w, val in surprise_prob.items():
    if w in surprise_sent or w in surprise_disgust_sent:
      train_given_surprise *= val
  train_surprise_prob.append(train_given_surprise)

  train_given_disgust = 1
  for w, val in disgust_prob.items():
    if w in disgust_sent or w in surprise_disgust_sent:
      train_given_disgust *= val
  train_disgust_prob.append(train_given_disgust)

maximum = 0
for i in train_disgust_prob:
  if i > maximum:
    maximum = i

print(maximum) # sadness highest probability score
print(train_sad_prob)
print(train_joy_prob)
print(train_fear_prob)
print(train_anger_prob)
print(train_surprise_prob)
print(train_disgust_prob)


1.0423687020873071e-72
[3.0169580222925573e-130, 1.3033211781523353e-203, 4.600178104240347e-183, 9.33407541895332e-142, 1.196870532289021e-153, 3.049495879676444e-180, 1.1143772920230902e-264, 6.533510483648811e-177, 4.222470926343854e-275, 2.645450569295026e-147, 5.451828980970555e-150, 3.244655168377485e-156, 1.775909271320215e-192, 6.145852357378303e-220, 3.6327170000849624e-168, 1.967651921621366e-176, 3.5038136597840063e-155, 1.387617927357794e-128, 6.428506686198511e-171, 1.7164453421061972e-256, 3.0400884954120845e-233, 2.1943408196794356e-137, 2.4292414935984807e-228, 2.516021383757577e-197, 1.742492870257295e-98, 4.46204578267754e-221, 6.047039139776245e-174]
[4.332198069637402e-99, 1.4211106995187109e-195, 1.7263925507866002e-174, 4.249353159796528e-117, 8.74605035883885e-160, 1.1800723426534097e-203, 1.1362514443317165e-284, 2.0584030819593015e-211, 0.0, 1.516953453909815e-136, 4.585750717345261e-158, 5.658370083457296e-145, 1.9880831031175342e-209, 1.5876385317475576e-220,

## Section 3.3

In [ ]:
S = 'As she hugged her daughter goodbye on the first day of college, she felt both sad to see her go and joyful knowing that she was embarking on a new and exciting chapter in her life.'
l = [word for word in S.split(' ')]


In [ ]:
# score for test sentence:
# score to test if sad: P(sad) * P(S | sadness)
test_given_sad = 1
for w, val in sad_prob.items():
  if w in l:
    #print(w)
    test_given_sad *= val
    #print(test_given_sad)

print(test_given_sad)
score_test_given_sad = p_sad * test_given_sad
print(score_test_given_sad)

3.596292277669418e-51
7.192584555338837e-52


In [ ]:
test_given_joy = 1
for w, val in joy_prob.items():
  if w in l:
    test_given_joy *= val

print(test_given_joy)
score_test_given_joy = p_joy * test_given_joy
print(score_test_given_joy)


1.595782839409849e-41
3.191565678819698e-42


In [ ]:
test_given_fear = 1
for w, val in fear_prob.items():
  if w in l:
    test_given_fear *= val

print(test_given_fear)
score_test_given_fear = p_fear * test_given_fear
print(score_test_given_fear)


5.2261677903748786e-36
1.0452335580749758e-36


In [ ]:
test_given_anger = 1
for w, val in anger_prob.items():
  if w in l:
    test_given_anger *= val

print(test_given_anger)
score_test_given_anger = p_anger * test_given_anger
print(score_test_given_anger)

2.1089115698742628e-33
2.8118820931656836e-34


In [ ]:
test_given_surprise = 1
for w, val in surprise_prob.items():
  if w in l:
    test_given_surprise *= val

print(test_given_surprise)
score_test_given_surprise = p_surprise * test_given_surprise
print(score_test_given_surprise)

3.163166525815443e-27
4.217555367753924e-28


In [ ]:
test_given_disgust = 1
for w, val in disgust_prob.items():
  if w in l:
    test_given_disgust *= val


print(test_given_disgust)
score_test_given_disgust = p_disgust * test_given_disgust
print(score_test_given_disgust)

2.5745837274344748e-30
3.432778303245966e-31


In [ ]:
highest_score = max(score_test_given_sad, score_test_given_joy, score_test_given_fear, score_test_given_anger, score_test_given_surprise, score_test_given_disgust)

if highest_score == score_test_given_sad:
  print(S, " : classfied in Sadness emotion class")
elif highest_score == score_test_given_joy:
  print(S, " : classfied in Joy emotion class")
elif highest_score == score_test_given_fear:
  print(S, " : classified in Fear emotion class")
elif highest_score == score_test_given_anger:
  print(S, " : classified in Anger emotion class")
elif highest_score == score_test_given_surprise:
  print(S, " : classfied in Surprise emotion class")
else:
  print(S, " : classified in Disgust emotion class")


As she hugged her daughter goodbye on the first day of college, she felt both sad to see her go and joyful knowing that she was embarking on a new and exciting chapter in her life.  : classfied in Surprise emotion class


# Section 4 - Evaluating Classifier on test set

In [ ]:
def BOW(tokens):
  d = dict()
  for word in tokens:
    d[word] = 0
  for word in tokens:
    d[word] += 1
  return d


In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

#testing_set
test1 = [] # sadness
test2 = [] # joy
test3 = [] # fear
test4 = [] # anger
test5 = [] # surprise
test6 = [] # disgust

test_words = list()

correct_predictions = 0
incorrect_predictions = 0
classify_testset = list()
classes = {1: "Sadness", 2: "Joy", 3: "Fear", 4: "Anger", 5: "Surprise", 6: "Disgust"}

for i in range(len(testing_set)):
  sad_sen = testing_set.iloc[i]['Sadness Sentences']
  joy_sen = testing_set.iloc[i]['Joy Sentences']
  fear_sen = testing_set.iloc[i]['Fear Sentences']
  anger_sen = testing_set.iloc[i]['Anger Sentences']
  surprise_sen = testing_set.iloc[i]['Surprise Sentence']
  disgust_sen = testing_set.iloc[i]['Disgust Sentences']
  sad_joy_sen = testing_set.iloc[i]['Sadness + Joy Sentences']
  fear_anger_sen = testing_set.iloc[i]['Fear + Anger Sentences']
  surprise_disgust_sen = testing_set.iloc[i]['Surprise + Disgust Sentences']
  sad_joy_fear_sen = testing_set.iloc[i]['Sadness + Joy + Fear Sentences']

  lst = [sad_sen, joy_sen, fear_sen, anger_sen, surprise_sen, disgust_sen, sad_joy_sen, fear_anger_sen, surprise_disgust_sen, sad_joy_fear_sen]
  for s in lst:
    words = s.split(" ")
    words = lower(words)
    for w in words:
      if w in stops:
        #print(w)
        words.remove(w)

    for w in words:
      if w not in test_words:
        test_words.append(w)

  testsent_given_sad = 1
  for w, val in sad_prob.items():
    if w in sad_sen or w in sad_joy_sen or w in sad_joy_fear_sen:
      testsent_given_sad *= val

  test1.append(testsent_given_sad)

  testsent_given_joy = 1
  for w, val in joy_prob.items():
    if w in joy_sen or w in sad_joy_sen or w in sad_joy_fear_sen:
      testsent_given_joy *= val
  test2.append(testsent_given_joy)

  testsent_given_fear = 1
  for w, val in fear_prob.items():
    if w in fear_sen or w in fear_anger_sen or w in sad_joy_fear_sen:
      testsent_given_fear *= val
  test3.append(testsent_given_fear)

  testsent_given_anger = 1
  for w, val in anger_prob.items():
    if w in anger_sen or w in fear_anger_sen:
      testsent_given_anger *= val
  test4.append(testsent_given_anger)

  testsent_given_surprise = 1
  for w, val in surprise_prob.items():
    if w in surprise_sen or w in surprise_disgust_sen:
      testsent_given_surprise *= val
  test5.append(testsent_given_surprise)

  testsent_given_disgust = 1
  for w, val in disgust_prob.items():
    if w in disgust_sen or w in surprise_disgust_sen:
      testsent_given_disgust *= val
  test6.append(testsent_given_disgust)

  highest_prob = max(testsent_given_sad, testsent_given_joy, testsent_given_fear, testsent_given_anger, testsent_given_surprise, testsent_given_disgust)
  print(highest_prob)

  if highest_prob == score_test_given_sad:
    classify_testset.append(1)
  elif highest_prob == score_test_given_joy:
    classify_testset.append(2)
  elif highest_prob == score_test_given_fear:
    classify_testset.append(3)
  elif highest_prob == score_test_given_anger:
    classify_testset.append(4)
  elif highest_prob == score_test_given_surprise:
    classify_testset.append(5)
  else:
    classify_testset.append(6)

print(test1) # prediction for sadness emotion
print(test2) # prediction for joy
print(test3) # prediction for fear
print(test4) # prediction for anger
print(test5) # prediction for surprise
print(test6) # prediction for disgust

#print()
#print("test words: ")
#test_words
testset_words_len = len(test_words)
#print(testset_words_len)

9.135158435366934e-78
1.8095324048077468e-66
9.743665797036007e-59
2.995033033841422e-54
[1.5691141504924176e-123, 6.408825024835406e-104, 9.607257749822485e-103, 8.806505820138869e-119]
[1.0336548741320218e-135, 2.7840447107334133e-94, 6.840291330664477e-116, 1.3685855980663173e-148]
[7.243720738735473e-129, 1.269479471076279e-117, 1.472986002435652e-113, 7.625489421591115e-126]
[7.138849531413432e-79, 8.591742386750363e-77, 2.5506447974056883e-83, 2.995033033841422e-54]
[1.6800795762362726e-81, 2.812104942561186e-67, 1.3842800124781896e-75, 1.1107675420060178e-94]
[9.135158435366934e-78, 1.8095324048077468e-66, 9.743665797036007e-59, 2.1803316596271726e-81]


## Section 4.1

In [ ]:
import seaborn as sn
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import classification_report

In [ ]:
y_true = ['Sadness', 'Sadness', 'Sadness', 'Sadness']
y_pred = []
labels = ['Sadness', 'Joy', 'Fear', 'Anger', 'Surprise', 'Disgust']
testing_set['Sadness Sentences']
for sentence in testing_set['Sadness Sentences']:
  words = [s for s in sentence.split(' ')]
  testgivensad = 1
  testgivenjoy = 1
  testgivenfear = 1
  testgivenanger = 1
  testgivensurprise = 1
  testgivendisgust = 1
  for w, val in sad_prob.items():
    if w in words:
      testgivensad *= val

  for w, val in joy_prob.items():
    if w in words:
      testgivenjoy *= val
  for w, val in fear_prob.items():
    if w in words:
      testgivenfear *= val
  for w, val in anger_prob.items():
    if w in words:
      testgivenanger *= val
  for w, val in surprise_prob.items():
    if w in words:
      testgivensurprise *= val
  for w, val in disgust_prob.items():
    if w in words:
      testgivendisgust *= val

  highestscore = max(testgivensad, testgivenjoy, testgivenfear, testgivenanger, testgivensurprise, testgivendisgust)
  #print(highestscore)
  if highestscore == testgivensad:
    y_pred.append('Sadness')
  elif highestscore == testgivenjoy:
    y_pred.append('Joy')
  elif highestscore == testgivenfear:
    y_pred.append('Fear')
  elif highestscore == testgivenanger:
    y_pred.append('Anger')
  elif highestscore == testgivensurprise:
    y_pred.append('Surprise')
  elif highestscore == testgivendisgust:
    y_pred.append('Disgust')

print(y_pred)
cm = confusion_matrix(y_true, y_pred, labels=labels)
print(cm)
print(classification_report(y_true, y_pred, target_names=['Sadness', 'Joy', 'Anger', 'Disgust']))


['Disgust', 'Anger', 'Sadness', 'Joy']
[[1 1 0 1 0 1]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
              precision    recall  f1-score   support

     Sadness       0.00      0.00      0.00         0
         Joy       0.00      0.00      0.00         0
       Anger       0.00      0.00      0.00         0
     Disgust       1.00      0.25      0.40         4

    accuracy                           0.25         4
   macro avg       0.25      0.06      0.10         4
weighted avg       1.00      0.25      0.40         4



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
y_true2 = ['Fear', 'Fear', 'Fear', 'Fear']
y_pred2 = []

for sentence in testing_set['Fear Sentences']:
  words = [s for s in sentence.split(' ')]
  testgivensad = 1
  testgivenjoy = 1
  testgivenfear = 1
  testgivenanger = 1
  testgivensurprise = 1
  testgivendisgust = 1
  for w, val in sad_prob.items():
    if w in words:
      testgivensad *= val

  for w, val in joy_prob.items():
    if w in words:
      testgivenjoy *= val

  for w, val in fear_prob.items():
    if w in words:
      testgivenfear *= val

  for w, val in anger_prob.items():
    if w in words:
      testgivenanger *= val

  for w, val in surprise_prob.items():
    if w in words:
      testgivensurprise *= val

  for w, val in disgust_prob.items():
    if w in words:
      testgivendisgust *= val

  highestscore = max(testgivensad, testgivenjoy, testgivenfear, testgivenanger, testgivensurprise, testgivendisgust)
  #print(highestscore)
  if highestscore == testgivensad:
    y_pred2.append('Sadness')
  elif highestscore == testgivenjoy:
    y_pred2.append('Joy')
  elif highestscore == testgivenfear:
    y_pred2.append('Fear')
  elif highestscore == testgivenanger:
    y_pred2.append('Anger')
  elif highestscore == testgivensurprise:
    y_pred2.append('Surprise')
  elif highestscore == testgivendisgust:
    y_pred2.append('Disgust')

print(y_pred2)
cm2 = confusion_matrix(y_true2, y_pred2, labels=labels)
print(cm2)

3.0434501076861677e-17
1.2938850902355487e-08
2.5976197180519934e-21
1.0251671110939915e-15
['Disgust', 'Surprise', 'Joy', 'Disgust']
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 1 0 0 1 2]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [ ]:
y_true3 = ['Anger', 'Anger', 'Anger', 'Anger']
y_pred3 = []

for sentence in testing_set['Anger Sentences']:
  words = [s for s in sentence.split(' ')]
  testgivensad = 1
  testgivenjoy = 1
  testgivenfear = 1
  testgivenanger = 1
  testgivensurprise = 1
  testgivendisgust = 1
  for w, val in sad_prob.items():
    if w in words:
      testgivensad *= val

  for w, val in joy_prob.items():
    if w in words:
      testgivenjoy *= val

  for w, val in fear_prob.items():
    if w in words:
      testgivenfear *= val

  for w, val in anger_prob.items():
    if w in words:
      testgivenanger *= val

  for w, val in surprise_prob.items():
    if w in words:
      testgivensurprise *= val

  for w, val in disgust_prob.items():
    if w in words:
      testgivendisgust *= val

  highestscore = max(testgivensad, testgivenjoy, testgivenfear, testgivenanger, testgivensurprise, testgivendisgust)
  if highestscore == testgivensad:
    y_pred3.append('Sadness')
  elif highestscore == testgivenjoy:
    y_pred3.append('Joy')
  elif highestscore == testgivenfear:
    y_pred3.append('Fear')
  elif highestscore == testgivenanger:
    y_pred3.append('Anger')
  elif highestscore == testgivensurprise:
    y_pred3.append('Surprise')
  elif highestscore == testgivendisgust:
    y_pred3.append('Disgust')

print(y_pred3)
cm3 = confusion_matrix(y_true3, y_pred3, labels=labels)
print(cm3)

['Disgust', 'Surprise', 'Surprise', 'Disgust']
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 2 2]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [ ]:
y_true4 = ['Surprise', 'Surprise', 'Surprise', 'Surprise']
y_pred4 = []
for sentence in testing_set['Surprise Sentence']:
  words = [s for s in sentence.split(' ')]
  testgivensad = 1
  testgivenjoy = 1
  testgivenfear = 1
  testgivenanger = 1
  testgivensurprise = 1
  testgivendisgust = 1
  for w, val in sad_prob.items():
    if w in words:
      testgivensad *= val

  for w, val in joy_prob.items():
    if w in words:
      testgivenjoy *= val

  for w, val in fear_prob.items():
    if w in words:
      testgivenfear *= val

  for w, val in anger_prob.items():
    if w in words:
      testgivenanger *= val

  for w, val in surprise_prob.items():
    if w in words:
      testgivensurprise *= val

  for w, val in disgust_prob.items():
    if w in words:
      testgivendisgust *= val

  highestscore = max(testgivensad, testgivenjoy, testgivenfear, testgivenanger, testgivensurprise, testgivendisgust)
  if highestscore == testgivensad:
    y_pred4.append('Sadness')
  elif highestscore == testgivenjoy:
    y_pred4.append('Joy')
  elif highestscore == testgivenfear:
    y_pred4.append('Fear')
  elif highestscore == testgivenanger:
    y_pred4.append('Anger')
  elif highestscore == testgivensurprise:
    y_pred4.append('Surprise')
  elif highestscore == testgivendisgust:
    y_pred4.append('Disgust')

print(y_pred4)
cm4 = confusion_matrix(y_true4, y_pred4, labels=labels)
print(cm4)

['Anger', 'Sadness', 'Sadness', 'Anger']
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [2 0 0 2 0 0]
 [0 0 0 0 0 0]]


In [ ]:
y_true5 = ['Disgust', 'Disgust', 'Disgust', 'Disgust']
y_pred5 = []

for sentence in testing_set['Disgust Sentences']:
  words = [s for s in sentence.split(' ')]
  testgivensad = 1
  testgivenjoy = 1
  testgivenfear = 1
  testgivenanger = 1
  testgivensurprise = 1
  testgivendisgust = 1
  for w, val in sad_prob.items():
    if w in words:
      testgivensad *= val

  for w, val in joy_prob.items():
    if w in words:
      testgivenjoy *= val

  for w, val in fear_prob.items():
    if w in words:
      testgivenfear *= val

  for w, val in anger_prob.items():
    if w in words:
      testgivenanger *= val

  for w, val in surprise_prob.items():
    if w in words:
      testgivensurprise *= val

  for w, val in disgust_prob.items():
    if w in words:
      testgivendisgust *= val

  highestscore = max(testgivensad, testgivenjoy, testgivenfear, testgivenanger, testgivensurprise, testgivendisgust)
  if highestscore == testgivensad:
    y_pred5.append('Sadness')
  elif highestscore == testgivenjoy:
    y_pred5.append('Joy')
  elif highestscore == testgivenfear:
    y_pred5.append('Fear')
  elif highestscore == testgivenanger:
    y_pred5.append('Anger')
  elif highestscore == testgivensurprise:
    y_pred5.append('Surprise')
  elif highestscore == testgivendisgust:
    y_pred5.append('Disgust')

print(y_pred5)
cm5 = confusion_matrix(y_true5, y_pred5, labels=labels)
print(cm5)

['Disgust', 'Disgust', 'Surprise', 'Joy']
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 1 0 0 1 2]]


In [ ]:
cm6 = cm + cm1 + cm2 + cm3 + cm4 + cm5
print(cm6)
y_pred6 = [y_pred, y_pred1, y_pred2, y_pred3, y_pred4, y_pred5]
print(y_pred6)
y_true6 = [y_true, y_true1, y_true2, y_true3, y_true4, y_true5]
print(y_true6)

[[1 1 0 1 0 1]
 [0 0 0 0 0 0]
 [0 2 0 0 2 4]
 [0 0 0 0 2 2]
 [2 0 0 2 0 0]
 [0 1 0 0 1 2]]
[['Disgust', 'Anger', 'Sadness', 'Joy'], ['Disgust', 'Disgust', 'Fear', 'Anger'], ['Disgust', 'Surprise', 'Joy', 'Disgust'], ['Disgust', 'Surprise', 'Surprise', 'Disgust'], ['Anger', 'Sadness', 'Sadness', 'Anger'], ['Disgust', 'Disgust', 'Surprise', 'Joy']]
[['Sadness', 'Sadness', 'Sadness', 'Sadness'], ['Joy', 'Joy', 'Joy', 'Joy'], ['Fear', 'Fear', 'Fear', 'Fear'], ['Anger', 'Anger', 'Anger', 'Anger'], ['Surprise', 'Surprise', 'Surprise', 'Surprise'], ['Disgust', 'Disgust', 'Disgust', 'Disgust']]


In [ ]:
df_cm = pd.DataFrame(cm6, labels, labels)
#ax = sn.heatmap(df_cm, annot=True, annot_kws={'size': 16}, square=True, cbar=False, fmt='g')
#ax.set_ylim(0, 6) #this manually corrects the cutoff issue in sns.heatmap found in matplotlib ver 3.1.1
#plt.xlabel('Predicted')
#plt.ylabel('Actual')
#ax.invert_yaxis() #optional
#plt.show()


In [ ]:

#print('Micro Preicision: {:.2f}'.format(precision_score(y_true, y_pred, average='micro')))
#print('Micro Recall: {:.2f}'.format(recall_score(y_true, y_pred, average='micro')))
#print('Micro F1-score: {:.2f}\n'.format(f1_score(y_true, y_pred, average='micro')))

#print('Micro Preicision: {:.2f}'.format(precision_score(y_true1, y_pred1, average='micro')))
#print('Micro Recall: {:.2f}'.format(recall_score(y_true1, y_pred1, average='micro')))
#print('Micro F1-score: {:.2f}\n'.format(f1_score(y_true1, y_pred1, average='micro')))

#print('Micro Preicision: {:.2f}'.format(precision_score(y_true2, y_pred2, average='micro')))
#print('Micro Recall: {:.2f}'.format(recall_score(y_true2, y_pred2, average='micro')))
#print('Micro F1-score: {:.2f}\n'.format(f1_score(y_true2, y_pred2, average='micro')))

#print('Micro Preicision: {:.2f}'.format(precision_score(y_true3, y_pred3, average='micro')))
#print('Micro Recall: {:.2f}'.format(recall_score(y_true3, y_pred3, average='micro')))
#print('Micro F1-score: {:.2f}\n'.format(f1_score(y_true3, y_pred3, average='micro')))

#print('Micro Preicision: {:.2f}'.format(precision_score(y_true4, y_pred4, average='micro')))
#print('Micro Recall: {:.2f}'.format(recall_score(y_true4, y_pred4, average='micro')))
#print('Micro F1-score: {:.2f}\n'.format(f1_score(y_true4, y_pred4, average='micro')))

#print('Micro Preicision: {:.2f}'.format(precision_score(y_true5, y_pred5, average='micro')))
#print('Micro Recall: {:.2f}'.format(recall_score(y_true5, y_pred5, average='micro')))
#print('Micro F1-score: {:.2f}\n'.format(f1_score(y_true5, y_pred5, average='micro')))


print('Classification Report')
print(classification_report(y_true, y_pred))

print(classification_report(y_true1, y_pred1))

print(classification_report(y_true2, y_pred2))

print(classification_report(y_true3, y_pred3))

print(classification_report(y_true4, y_pred4))

print(classification_report(y_true5, y_pred))


Classification Report
              precision    recall  f1-score   support

       Anger       0.00      0.00      0.00         0
     Disgust       0.00      0.00      0.00         0
         Joy       0.00      0.00      0.00         0
     Sadness       1.00      0.25      0.40         4

    accuracy                           0.25         4
   macro avg       0.25      0.06      0.10         4
weighted avg       1.00      0.25      0.40         4

              precision    recall  f1-score   support

       Anger       0.00      0.00      0.00       0.0
     Disgust       0.00      0.00      0.00       0.0
        Fear       0.00      0.00      0.00       0.0
         Joy       0.00      0.00      0.00       4.0

    accuracy                           0.00       4.0
   macro avg       0.00      0.00      0.00       4.0
weighted avg       0.00      0.00      0.00       4.0

              precision    recall  f1-score   support

     Disgust       0.00      0.00      0.00       0.0

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: Undefin

## Section 4.2

In [ ]:
y_true1 = ['Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy', 'Joy']
y_pred1 = []
sent1 = 'Pleased with her performance, Maggie was able to win the tournament and finally wear the first place medal she longed for.'
sent2 = 'The pride of their accomplishment welled up within their hearts as the crowd cheered on.'
sent3 = 'I was grateful to have met him, his youthful attitude helped me reinvigorate my own zest for life.'
sent4 = 'The father looked at his son’s youthful enjoyment as he won the basketball game with his teammates.'

sent5 = 'Loving, passionate sex always ends with a magical orgasm.'
sent6 = 'The moment I laid my eyes on the acceptance letter from my dream school, an overwhelming feeling of elation and achievement washed over me.'
sent7 = 'The music that was playing in the cafe was as delightful as a sunny, afternoon picnic with close friends.'
sent8 = 'John achieved his lifelong goal of getting the most prestigious award for one of his art pieces.'
sent9 = 'The elegant party was filled with exquisite decorations and delightful laughter, lifting everyone’s spirit.'
# When I was preprocessing my data into training, validation, and testing, and there were 45 rows total testing set has 4 sentences to test.
#for sent in testing_set['Joy Sentences']:
#  print(sent)
#for i in range(len(testing_set['Joy Sentences'])):
  #print(i)
  #sent1 = testing_set[0]['Joy Sentences']
  #sent2 = testing_set[1]['Joy Sentences']
  #sent3 = testing_set[2]['Joy Sentences']
  #sent4 = testing_set[3]['Joy Sentences']

# sent1
testgivensad = 1
testgivenjoy = 1
testgivenfear = 1
testgivenanger = 1
testgivensurprise = 1
testgivendisgust = 1

words = [s for s in sent1.split(' ')]
for w, val in sad_prob.items():
  if w in words:
    testgivensad *= val

for w, val in joy_prob.items():
  if w in words:
    testgivenjoy *= val

for w, val in fear_prob.items():
  if w in words:
    testgivenfear *= val

for w, val in anger_prob.items():
  if w in words:
    testgivenanger *= val

for w, val in surprise_prob.items():
  if w in words:
    testgivensurprise *= val

for w, val in disgust_prob.items():
  if w in words:
    testgivendisgust *= val

highestscore = max(testgivensad, testgivenjoy, testgivenfear, testgivenanger, testgivensurprise, testgivendisgust)
if highestscore == testgivensad:
  y_pred1.append('Sadness')
elif highestscore == testgivenjoy:
  y_pred1.append('Joy')
elif highestscore == testgivenfear:
  y_pred1.append('Fear')
elif highestscore == testgivenanger:
  y_pred1.append('Anger')
elif highestscore == testgivensurprise:
  y_pred1.append('Surprise')
elif highestscore == testgivendisgust:
  y_pred1.append('Disgust')


# sent2
testgivensad = 1
testgivenjoy = 1
testgivenfear = 1
testgivenanger = 1
testgivensurprise = 1
testgivendisgust = 1
words1 = [s for s in sent2.split(' ')]
for w, val in sad_prob.items():
  if w in words1:
    testgivensad *= val

for w, val in joy_prob.items():
  if w in words1:
    testgivenjoy *= val

for w, val in fear_prob.items():
  if w in words1:
    testgivenfear *= val

for w, val in anger_prob.items():
  if w in words1:
    testgivenanger *= val

for w, val in surprise_prob.items():
  if w in words1:
    testgivensurprise *= val

for w, val in disgust_prob.items():
  if w in words1:
    testgivendisgust *= val

highestscore1 = max(testgivensad, testgivenjoy, testgivenfear, testgivenanger, testgivensurprise, testgivendisgust)
if highestscore1 == testgivensad:
  y_pred1.append('Sadness')
elif highestscore1 == testgivenjoy:
  y_pred1.append('Joy')
elif highestscore1 == testgivenfear:
  y_pred1.append('Fear')
elif highestscore1 == testgivenanger:
  y_pred1.append('Anger')
elif highestscore1 == testgivensurprise:
  y_pred1.append('Surprise')
elif highestscore1 == testgivendisgust:
  y_pred1.append('Disgust')

# sent3
testgivensad = 1
testgivenjoy = 1
testgivenfear = 1
testgivenanger = 1
testgivensurprise = 1
testgivendisgust = 1
words2 = [s for s in sent3.split(' ')]
for w, val in sad_prob.items():
  if w in words2:
    testgivensad *= val

for w, val in joy_prob.items():
  if w in words2:
    testgivenjoy *= val

for w, val in fear_prob.items():
  if w in words2:
    testgivenfear *= val

for w, val in anger_prob.items():
  if w in words2:
    testgivenanger *= val

for w, val in surprise_prob.items():
  if w in words2:
    testgivensurprise *= val

for w, val in disgust_prob.items():
  if w in words2:
    testgivendisgust *= val

highestscore2 = max(testgivensad, testgivenjoy, testgivenfear, testgivenanger, testgivensurprise, testgivendisgust)
if highestscore2 == testgivensad:
  y_pred1.append('Sadness')
elif highestscore2 == testgivenjoy:
  y_pred1.append('Joy')
elif highestscore2 == testgivenfear:
  y_pred1.append('Fear')
elif highestscore2 == testgivenanger:
  y_pred1.append('Anger')
elif highestscore2 == testgivensurprise:
  y_pred1.append('Surprise')
elif highestscore2 == testgivendisgust:
  y_pred1.append('Disgust')


# sent4
testgivensad = 1
testgivenjoy = 1
testgivenfear = 1
testgivenanger = 1
testgivensurprise = 1
testgivendisgust = 1
words3 = [s for s in sent4.split(' ')]
for w, val in sad_prob.items():
  if w in words3:
    testgivensad *= val

for w, val in joy_prob.items():
  if w in words3:
    testgivenjoy *= val

for w, val in fear_prob.items():
  if w in words3:
    testgivenfear *= val

for w, val in anger_prob.items():
  if w in words3:
    testgivenanger *= val

for w, val in surprise_prob.items():
  if w in words3:
    testgivensurprise *= val

for w, val in disgust_prob.items():
  if w in words3:
    testgivendisgust *= val

highestscore3 = max(testgivensad, testgivenjoy, testgivenfear, testgivenanger, testgivensurprise, testgivendisgust)
if highestscore3 == testgivensad:
  y_pred1.append('Sadness')
elif highestscore3 == testgivenjoy:
  y_pred1.append('Joy')
elif highestscore3 == testgivenfear:
  y_pred1.append('Fear')
elif highestscore3 == testgivenanger:
  y_pred1.append('Anger')
elif highestscore3 == testgivensurprise:
  y_pred1.append('Surprise')
elif highestscore3 == testgivendisgust:
  y_pred1.append('Disgust')


# sent5
testgivensad = 1
testgivenjoy = 1
testgivenfear = 1
testgivenanger = 1
testgivensurprise = 1
testgivendisgust = 1
words4 = [s for s in sent5.split(' ')]
for w, val in sad_prob.items():
  if w in words4:
    testgivensad *= val

for w, val in joy_prob.items():
  if w in words4:
    testgivenjoy *= val

for w, val in fear_prob.items():
  if w in words4:
    testgivenfear *= val

for w, val in anger_prob.items():
  if w in words4:
    testgivenanger *= val

for w, val in surprise_prob.items():
  if w in words4:
    testgivensurprise *= val

for w, val in disgust_prob.items():
  if w in words4:
    testgivendisgust *= val

highestscore4 = max(testgivensad, testgivenjoy, testgivenfear, testgivenanger, testgivensurprise, testgivendisgust)
if highestscore4 == testgivensad:
  y_pred1.append('Sadness')
elif highestscore4 == testgivenjoy:
  y_pred1.append('Joy')
elif highestscore4 == testgivenfear:
  y_pred1.append('Fear')
elif highestscore4 == testgivenanger:
  y_pred1.append('Anger')
elif highestscore4 == testgivensurprise:
  y_pred1.append('Surprise')
elif highestscore4 == testgivendisgust:
  y_pred1.append('Disgust')


# sent6
testgivensad = 1
testgivenjoy = 1
testgivenfear = 1
testgivenanger = 1
testgivensurprise = 1
testgivendisgust = 1
words5 = [s for s in sent6.split(' ')]
for w, val in sad_prob.items():
  if w in words5:
    testgivensad *= val

for w, val in joy_prob.items():
  if w in words5:
    testgivenjoy *= val

for w, val in fear_prob.items():
  if w in words5:
    testgivenfear *= val

for w, val in anger_prob.items():
  if w in words5:
    testgivenanger *= val

for w, val in surprise_prob.items():
  if w in words5:
    testgivensurprise *= val

for w, val in disgust_prob.items():
  if w in words5:
    testgivendisgust *= val

highestscore5 = max(testgivensad, testgivenjoy, testgivenfear, testgivenanger, testgivensurprise, testgivendisgust)
if highestscore5 == testgivensad:
  y_pred1.append('Sadness')
elif highestscore5 == testgivenjoy:
  y_pred1.append('Joy')
elif highestscore5 == testgivenfear:
  y_pred1.append('Fear')
elif highestscore5 == testgivenanger:
  y_pred1.append('Anger')
elif highestscore5 == testgivensurprise:
  y_pred1.append('Surprise')
elif highestscore5 == testgivendisgust:
  y_pred1.append('Disgust')


# sent7
testgivensad = 1
testgivenjoy = 1
testgivenfear = 1
testgivenanger = 1
testgivensurprise = 1
testgivendisgust = 1
words6 = [s for s in sent7.split(' ')]
for w, val in sad_prob.items():
  if w in words6:
    testgivensad *= val

for w, val in joy_prob.items():
  if w in words6:
    testgivenjoy *= val

for w, val in fear_prob.items():
  if w in words6:
    testgivenfear *= val

for w, val in anger_prob.items():
  if w in words6:
    testgivenanger *= val

for w, val in surprise_prob.items():
  if w in words6:
    testgivensurprise *= val

for w, val in disgust_prob.items():
  if w in words6:
    testgivendisgust *= val

highestscore6 = max(testgivensad, testgivenjoy, testgivenfear, testgivenanger, testgivensurprise, testgivendisgust)
if highestscore6 == testgivensad:
  y_pred1.append('Sadness')
elif highestscore6 == testgivenjoy:
  y_pred1.append('Joy')
elif highestscore6 == testgivenfear:
  y_pred1.append('Fear')
elif highestscore6 == testgivenanger:
  y_pred1.append('Anger')
elif highestscore6 == testgivensurprise:
  y_pred1.append('Surprise')
elif highestscore6 == testgivendisgust:
  y_pred1.append('Disgust')



# sent8
testgivensad = 1
testgivenjoy = 1
testgivenfear = 1
testgivenanger = 1
testgivensurprise = 1
testgivendisgust = 1
words7 = [s for s in sent8.split(' ')]
for w, val in sad_prob.items():
  if w in words7:
    testgivensad *= val

for w, val in joy_prob.items():
  if w in words7:
    testgivenjoy *= val

for w, val in fear_prob.items():
  if w in words7:
    testgivenfear *= val

for w, val in anger_prob.items():
  if w in words7:
    testgivenanger *= val

for w, val in surprise_prob.items():
  if w in words7:
    testgivensurprise *= val

for w, val in disgust_prob.items():
  if w in words7:
    testgivendisgust *= val

highestscore7 = max(testgivensad, testgivenjoy, testgivenfear, testgivenanger, testgivensurprise, testgivendisgust)
if highestscore7 == testgivensad:
  y_pred1.append('Sadness')
elif highestscore7 == testgivenjoy:
  y_pred1.append('Joy')
elif highestscore7 == testgivenfear:
  y_pred1.append('Fear')
elif highestscore7 == testgivenanger:
  y_pred1.append('Anger')
elif highestscore7 == testgivensurprise:
  y_pred1.append('Surprise')
elif highestscore7 == testgivendisgust:
  y_pred1.append('Disgust')


# sent9
testgivensad = 1
testgivenjoy = 1
testgivenfear = 1
testgivenanger = 1
testgivensurprise = 1
testgivendisgust = 1
words8 = [s for s in sent9.split(' ')]
for w, val in sad_prob.items():
  if w in words8:
    testgivensad *= val

for w, val in joy_prob.items():
  if w in words8:
    testgivenjoy *= val

for w, val in fear_prob.items():
  if w in words8:
    testgivenfear *= val

for w, val in anger_prob.items():
  if w in words8:
    testgivenanger *= val

for w, val in surprise_prob.items():
  if w in words8:
    testgivensurprise *= val

for w, val in disgust_prob.items():
  if w in words8:
    testgivendisgust *= val

highestscore8 = max(testgivensad, testgivenjoy, testgivenfear, testgivenanger, testgivensurprise, testgivendisgust)
if highestscore8 == testgivensad:
  y_pred1.append('Sadness')
elif highestscore8 == testgivenjoy:
  y_pred1.append('Joy')
elif highestscore8 == testgivenfear:
  y_pred1.append('Fear')
elif highestscore8 == testgivenanger:
  y_pred1.append('Anger')
elif highestscore8 == testgivensurprise:
  y_pred1.append('Surprise')
elif highestscore8 == testgivendisgust:
  y_pred1.append('Disgust')


print(y_pred1)
cm1 = confusion_matrix(y_true1, y_pred1, labels=labels)
print(cm1)


['Disgust', 'Disgust', 'Fear', 'Anger', 'Fear', 'Disgust', 'Joy', 'Sadness', 'Joy']
[[0 0 0 0 0 0]
 [1 2 2 1 0 3]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [ ]:
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_true1, y_pred1)
print('Confusion Matrix\n')
print(confusion)

#importing accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
print('\nAccuracy: {:.2f}\n'.format(accuracy_score(y_true1, y_pred1)))

print('Micro Precision: {:.2f}'.format(precision_score(y_true1, y_pred1, average='micro')))
print('Micro Recall: {:.2f}'.format(recall_score(y_true1, y_pred1, average='micro')))
print('Micro F1-score: {:.2f}\n'.format(f1_score(y_true1, y_pred1, average='micro')))

print('Macro Precision: {:.2f}'.format(precision_score(y_true1, y_pred1, average='macro')))
print('Macro Recall: {:.2f}'.format(recall_score(y_true1, y_pred1, average='macro')))
print('Macro F1-score: {:.2f}\n'.format(f1_score(y_true1, y_pred1, average='macro')))

print('Weighted Precision: {:.2f}'.format(precision_score(y_true1, y_pred1, average='weighted')))
print('Weighted Recall: {:.2f}'.format(recall_score(y_true1, y_pred1, average='weighted')))
print('Weighted F1-score: {:.2f}'.format(f1_score(y_true1, y_pred1, average='weighted')))

from sklearn.metrics import classification_report
print('\nClassification Report\n')
#print(classification_report(y_true1, y_pred1, target_names=['Sadness', 'Joy', 'Fear', 'Anger', 'Surprise', 'Disgust']))


Confusion Matrix

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [1 3 2 2 1]
 [0 0 0 0 0]]

Accuracy: 0.22

Micro Precision: 0.22
Micro Recall: 0.22
Micro F1-score: 0.22

Macro Precision: 0.20
Macro Recall: 0.04
Macro F1-score: 0.07

Weighted Precision: 1.00
Weighted Recall: 0.22
Weighted F1-score: 0.36

Classification Report



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


### Ignore BELOW

In [ ]:
import numpy as np
data = pd.read_csv('CS173-published-sheet.csv')

from collections import Counter, OrderedDict

data = data.drop(drop_columns, axis=1).dropna()
data

training_set = data[2:29]
validation_set = data[30:40]
#print(validation_set)
testing_set = data[41:]
#print(testing_set)

cnt = Counter()
total_words = 0
for sentence in testing_set['Sadness Sentences']:
  total_words += len(sentence)
  sentence = sentence.split(' ')
  for word in sentence:
    cnt[word] += 1

ordered_cnt = OrderedDict(cnt.most_common())
ordered_cnt

num_words_threshold = 9451

unique_words_90 = list(OrderedDict(cnt.most_common(num_words_threshold)).keys())
unique_words_90

['the',
 'in',
 'love',
 'to',
 'of',
 'he',
 'his',
 'is',
 'just',
 'that',
 'your',
 'me',
 'He',
 'was',
 'distraught',
 'by',
 'horrors',
 'saw',
 'during',
 'time',
 'war.\r\n',
 'Grief,',
 'I’ve',
 'learned,',
 'really',
 'love.',
 'It’s',
 'all',
 'you',
 'want',
 'give,',
 'but',
 'cannot.\r\nAll',
 'unspent',
 'gathers',
 'up',
 'corners',
 'eyes,',
 'lump',
 'your\r\nthroat,',
 'and',
 'hollow',
 'part',
 'chest.',
 'Grief',
 'with',
 'no',
 'place',
 'go.',
 'She',
 'abandoned',
 'last',
 'night',
 'after',
 'saying',
 'some',
 'wretched',
 'things',
 'at',
 'the\r\nparty.\r',
 'Richard',
 'lowered',
 'head',
 'disbelief',
 'as',
 'was\r\nwrongfully',
 'accused',
 'robbing',
 'bank.']

In [ ]:
from sklearn.model_selection import train_test_split

#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=0)

from sklearn.naive_bayes import MultinomialNB

#nb = MultinomialNB()
#nb.fit(X_train, y_train)
#y_pred = nb.predict(X_test)
#y_pred

from sklearn.metrics import confusion_matrix
#cm = confusion_matrix(y_test, y_pred)
#print(cm)
